import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header/Header";
import NavigationBar from "./components/NavigationBar/NavigationBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Diplomatic View",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    //header-nav-main-footer
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header style={{ padding: "12px 12px 6px", boxShadow: "0 0 2px 0" }}>
          <Header />
        </header>

        <nav style={{ padding: "8px 12px", boxShadow: "0 0 2px 0" }}>
          <NavigationBar />
        </nav>

        <main style={{ padding: "0 12px" }}>{children}</main>
        <footer style={{ padding: "0 12px" }}></footer>
      </body>
    </html>
  );
}
